### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by janz420** [qing762/exitlag-auto-signup#5]
Due to the inner workings of the module, it is needed to browse programmatically.
NEVER use the gui to navigate (Using your keybord and mouse) as it will causes POSSIBLE DETECTION!
The script will do the entire job itself.

`
Traceback (most recent call last):
  File "C:\Users\MyComputer\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\MyComputer\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\MyComputer\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\MyComputer\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 52, in <module>
    token = request.post(
  File "C:\Users\MyComputer\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by qing762** [comment]
[#4] Known issue. Just run the script one more time.

**Comment by janz420** [comment]
> Is Google Chrome (not Chromium) installed? If yes, try using a VPN / rerun the script. With the output you give, it seems like you have a reply from Mail.TM but it's not in JSON format.

I'm running chrome, it solved using VPN but there is new error.


Making [uc_driver.exe 118.0.5993.70] executable ...
[uc_driver.exe 118.0.5993.70] is now ready for use!

Traceback (most recent call last):
  File "main.py", line 69, in <module>
    firstnameelement = browser.find_element(By.NAME, "firstname")
  File "C:\Users\MyComputer\AppData\Roaming\Python\Python38\site-packages\seleniumbase\core\sb_driver.py", line 19, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\MyComputer\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 738, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\MyComputer\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "C:\Users\MyComputer\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="firstname"]"}
  (Session info: chrome=118.0.5993.89); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00007FF66DDF8EF2+54786]
        (No symbol) [0x00007FF66DD65612]
        (No symbol) [0x00007FF66DC1A64B]
        (No symbol) [0x00007FF66DC5B79C]
        (No symbol) [0x00007FF66DC5B91C]
        (No symbol) [0x00007FF66DC96D87]
        (No symbol) [0x00007FF66DC7BEAF]
        (No symbol) [0x00007FF66DC94D02]
        (No symbol) [0x00007FF66DC7BC43]
        (No symbol) [0x00007FF66DC50941]
        (No symbol) [0x00007FF66DC51B84]
        GetHandleVerifier [0x00007FF66E147F52+3524194]
        GetHandleVerifier [0x00007FF66E19D800+3874576]
        GetHandleVerifier [0x00007FF66E195D7F+3843215]
        GetHandleVerifier [0x00007FF66DE95086+694166]
        (No symbol) [0x00007FF66DD70A88]
        (No symbol) [0x00007FF66DD6CA94]
        (No symbol) [0x00007FF66DD6CBC2]
        (No symbol) [0x00007FF66DD5CC83]
        BaseThreadInitThunk [0x00007FFC5542257D+29]
        RtlUserThreadStart [0x00007FFC5602AA78+40]

**Comment by qing762** [comment]
It's really hard to determine the problem without a image / recording of the Chrome browser.
The problem you're having now is the browser cannot find the element, therefore error is produced.
Probably you ran into a human verification, try to not use the VPN.

The first error shouldn't be happening, either it's your IP address got blocked or rejected from Mail.TM or either it's a bug. Try rerun the script.
